manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: petejohanson
      url-base: https://github.com/petejohanson
  projects:
    - name: zmk
      remote: petejohanson
      revision: keymaps/user-keymap-infrastructure-refactor
      import: app/west.yml
  self:
    path: manifest-dir
