manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: keymaps/user-keymap-infrastructure-refactor
      import: app/west.yml
  self:
    path: manifest-dir
